let rules = {
  floor: [],
  hole: [
    { tileIndex:  0, map: { n: "!hole", e: "!hole", s: "!hole", w: "!hole"} },
    { tileIndex:  1, map: { n:  "hole", e: "!hole", s: "!hole", w: "!hole"} },
    { tileIndex:  2, map: { n: "!hole", e:  "hole", s: "!hole", w: "!hole"} },
    { tileIndex:  3, map: { n:  "hole", e:  "hole", s: "!hole", w: "!hole"} },
    { tileIndex:  4, map: { n: "!hole", e: "!hole", s:  "hole", w: "!hole"} },
    { tileIndex:  5, map: { n:  "hole", e: "!hole", s:  "hole", w: "!hole"} },
    { tileIndex:  6, map: { n: "!hole", e:  "hole", s:  "hole", w: "!hole"} },
    { tileIndex:  7, map: { n:  "hole", e:  "hole", s:  "hole", w: "!hole"} },
    { tileIndex:  8, map: { n: "!hole", e: "!hole", s: "!hole", w:  "hole"} },
    { tileIndex:  9, map: { n:  "hole", e: "!hole", s: "!hole", w:  "hole"} },
    { tileIndex: 10, map: { n: "!hole", e:  "hole", s: "!hole", w:  "hole"} },
    { tileIndex: 11, map: { n:  "hole", e:  "hole", s: "!hole", w:  "hole"} },
    { tileIndex: 12, map: { n: "!hole", e: "!hole", s:  "hole", w:  "hole"} },
    { tileIndex: 13, map: { n:  "hole", e: "!hole", s:  "hole", w:  "hole"} },
    { tileIndex: 14, map: { n: "!hole", e:  "hole", s:  "hole", w:  "hole"} },
    { tileIndex: 15, map: { n:  "hole", e:  "hole", s:  "hole", w:  "hole"} },
  ],
  ceiling: [
    { tileIndex: {row: 4, col:1}, map: { n:"!ceiling", w:"!ceiling", e:"!ceiling", s:"!ceiling" } }, // isolated "pillar" ceilings
    // 0 tile
    { tileIndex: {row: 0, col:1}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 0, col:2}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 0, col:3}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 0, col:4}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 0, col:5}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 0, col:6}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },

    { tileIndex: {row: 1, col:0}, map: { n:"!ceiling", w:"!ceiling", e:"!ceiling", s:"ceiling" } },
    { tileIndex: {row: 1, col:1}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 1, col:2}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 1, col:3}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    // variant ceiling
    { tileIndex: {row: 1, col:5}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 1, col:6}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },

    { tileIndex: {row: 2, col:0}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 2, col:1}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 2, col:2}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 2, col:3}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    // variant ceiling
    { tileIndex: {row: 2, col:5}, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 2, col:6}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },

    { tileIndex: {row: 3, col:0}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 3, col:1}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 3, col:2}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 3, col:3}, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 3, col:4}, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 3, col:5}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 3, col:6}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },

    { tileIndex: {row: 4, col:0}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 4, col:1}, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 4, col:2}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 4, col:3}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 4, col:4}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 4, col:5}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 4, col:6}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"!ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },

    { tileIndex: {row: 5, col:0}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 5, col:1}, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 5, col:2}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 5, col:3}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: {row: 5, col:4}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 5, col:5}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: {row: 5, col:6}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },

    { tileIndex: {row: 6, col:0}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:1}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:2}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:3}, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:4}, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:5}, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: {row: 6, col:6}, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },

    // Put this rule up top to make clearing screen faster.
    { tileIndex: 24, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },

    // --- Row 1 ---
    { tileIndex:  6, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"!ceiling", e:"!ceiling", s:"ceiling"} },
    { tileIndex:  7, map: { n:"!ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex:  8, map: { n:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex:  9, map: { n:"!ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling" } },
    { tileIndex: 10, map: { n:"!ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 11, map: { n:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 12, map: { n:"!ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling" } },
    { tileIndex: 13, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling"} },
    { tileIndex: 14, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling"} },
    { tileIndex: 15, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling"} },

    // --- Row 2 ---
    { tileIndex: 22, map: { n:"ceiling", w:"!ceiling", e:"!ceiling", s:"ceiling" } },
    { tileIndex: 23, map: { n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"ceiling" } },
    //{ tileIndex: 24, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 25, map: { nw:"ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling" } },
    { tileIndex: 26, map: { n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 27, map: { nw:"!ceiling", n:"!ceiling", ne:"!ceiling", w:"!ceiling", e:"!ceiling", sw:"!ceiling", s:"!ceiling", se:"!ceiling" } },
    { tileIndex: 28, map: { nw:"!ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling" } },
    { tileIndex: 29, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 30, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 31, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },

    // --- Row 3 ---
    { tileIndex: 38, map: { n:"ceiling", w:"!ceiling", e:"!ceiling", s:"!ceiling" } },
    { tileIndex: 39, map: { n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 40, map: { nw:"ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 41, map: { nw:"ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", s:"!ceiling" } },
    { tileIndex: 42, map: { n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 43, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 44, map: { nw:"!ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", s:"!ceiling" } },
    { tileIndex: 45, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 46, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 47, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"ceiling" } },

    // --- Row 4 ---
    { tileIndex: 55, map: { n:"!ceiling", w:"!ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 56, map: { n:"!ceiling", w:"ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 57, map: { n:"!ceiling", w:"ceiling", e:"!ceiling", s:"!ceiling" } },
    { tileIndex: 58, map: { n:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 59, map: { nw:"ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", sw:"!ceiling", s:"ceiling" } },
    { tileIndex: 60, map: { n:"ceiling", ne:"ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 61, map: { n:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 62, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 63, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"!ceiling" } },

    // --- Row 5 ---
    { tileIndex: 72, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 73, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 74, map: { n:"ceiling", ne:"!ceiling", w:"!ceiling", e:"ceiling", s:"ceiling", se:"ceiling" } },
    { tileIndex: 75, map: { nw:"!ceiling", n:"ceiling", ne:"ceiling", w:"ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 76, map: { nw:"ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", s:"!ceiling" } },
    { tileIndex: 77, map: { nw:"!ceiling", n:"ceiling", w:"ceiling", e:"!ceiling", sw:"ceiling", s:"ceiling" } },
    { tileIndex: 78, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"ceiling", s:"ceiling", se:"!ceiling" } },
    { tileIndex: 79, map: { nw:"!ceiling", n:"ceiling", ne:"!ceiling", w:"ceiling", e:"ceiling", sw:"!ceiling", s:"ceiling", se:"ceiling" } },
  ],
  wall: []
};
